### ISSUE TITLE
Week 07 Day 3 - Double Back - 

### ISSUE THREAD

**Issue by mdewey** [Alexiskjg16/Assignments#28]
Over the past couple of weeks we have been learning React and did a variety of projects; and over the last week we have learned a new framework, Vue.js. For this project, go back to a selected project that we did in React and recreate it using Vue.js.

## Requirements

* Recreate a React App in Vue

### Explorer Mode

- [x] Recreate `Color Picker`. 

### Adventure Mode
- [ ] Recreate `Snowman` 

### Epic Mode
- [ ] Recreate `Minesweeper`
 

 *NOTE* Remember that you should also be working on your capstone project this weekend as well.

**Comment by Alexiskjg16** [comment]
https://github.com/Alexiskjg16/VueColors

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/3ohs4rqJ6TiwuTQpiM/200w_d.gif)
